### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by Au3C2** [lvyufeng/Megatron-MS#10]
**Describe the bug**
ModuleNotFoundError: No module named 'torch._six'

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.
```python
Traceback (most recent call last):
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pretrain_gpt.py", line 46, in <module>
    from pangu.training.training import pretrain
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/training/training.py", line 64, in <module>
    from pangu.training.utils import BatchCollator
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/training/utils.py", line 13, in <module>
    from ..datasets.multimodal_dataset import SophonPromptText, SigmaPromptText, LlamaPromptText
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/datasets/multimodal_dataset.py", line 24, in <module>
    from torchvision import transforms
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/datasets/_optical_flow.py", line 13, in <module>
    from .utils import verify_str_arg
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/datasets/utils.py", line 22, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID
 - PyTorch version
 - CUDA version
 - NCCL version

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by lvyufeng** [comment]
done
