### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Au3C2** [lvyufeng/Megatron-MS#12]
**Describe the bug**
ModuleNotFoundError: No module named 'utils'

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.
```bash
Traceback (most recent call last):
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pretrain_gpt.py", line 46, in <module>
    from pangu.training.training import pretrain
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/training/training.py", line 64, in <module>
    from pangu.training.utils import BatchCollator
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/training/utils.py", line 13, in <module>
    from ..datasets.multimodal_dataset import SophonPromptText, SigmaPromptText, LlamaPromptText
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/datasets/multimodal_dataset.py", line 24, in <module>
    from torchvision import transforms
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/__init__.py", line 4, in <module>
    from torchvision import datasets
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/datasets/__init__.py", line 11, in <module>
    from .fakedata import FakeData
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/datasets/fakedata.py", line 5, in <module>
    from torchvision import transforms
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/transforms/transforms.py", line 15, in <module>
    from .functional import _is_numpy, _is_numpy_image
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/transforms/functional.py", line 23, in <module>
    from . import functional_tensor as F_t
  File "/path/to/Megatron-MS/Megatron-MS/torchvision/transforms/functional_tensor.py", line 14, in <module>
    from utils import graph_mode_condition
ModuleNotFoundError: No module named 'utils'

```
**Environment (please complete the following information):**
 - Megatron-LM commit ID
 - PyTorch version
 - CUDA version
 - NCCL version

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by lvyufeng** [comment]
done
