### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'torch.nn.utils.rnn'

### ISSUE THREAD

**Issue by Au3C2** [lvyufeng/Megatron-MS#2]
**Describe the bug**
Megatron-MS/torch/distributed/utils.py

`from torch.nn.utils.rnn import PackedSequence`

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.
```log
Traceback (most recent call last):
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pretrain_gpt.py", line 12, in <module>
    import pangu
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/__init__.py", line 19, in <module>
    import mindspeed.megatron_adaptor 
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/third_party/MindSpeed/mindspeed/megatron_adaptor.py", line 6, in <module>
    from torch_npu.contrib import transfer_to_npu
  File "/path/to/miniconda3/envs/linx/lib/python3.9/site-packages/torch_npu/__init__.py", line 12, in <module>
    from torch.distributed.fsdp import sharded_grad_scaler
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/fsdp/__init__.py", line 1, in <module>
    from ._flat_param import FlatParameter as FlatParameter
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/fsdp/_flat_param.py", line 31, in <module>
    from torch.distributed.fsdp._common_utils import (
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/fsdp/_common_utils.py", line 32, in <module>
    from torch.distributed.algorithms._checkpoint.checkpoint_wrapper import (
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 11, in <module>
    from torch.distributed.utils import _pack_kwargs, _replace_by_prefix, _unpack_kwargs
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/utils.py", line 21, in <module>
    from torch.nn.utils.rnn import PackedSequence
ModuleNotFoundError: No module named 'torch.nn.utils.rnn'
```

**Comment by Au3C2** [comment]
did not using fsdp
