### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'torch.testing'

### ISSUE THREAD

**Issue by Au3C2** [lvyufeng/Megatron-MS#7]
**Describe the bug**
ModuleNotFoundError: No module named 'torch.testing'

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.
```bash
Traceback (most recent call last):
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pretrain_gpt.py", line 12, in <module>
    import pangu
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/PanGu/pangu/__init__.py", line 19, in <module>
    import mindspeed.megatron_adaptor
  File "/path/to/Megatron-MS/38Bv3/pangu_sophon_pytorch-master/third_party/MindSpeed/mindspeed/megatron_adaptor.py", line 6, in <module>
    from torch_npu.contrib import transfer_to_npu
  File "/path/to/miniconda3/envs/linx/lib/python3.9/site-packages/torch_npu/__init__.py", line 12, in <module>
    from torch.distributed.fsdp import sharded_grad_scaler
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/fsdp/__init__.py", line 1, in <module>
    from ._flat_param import FlatParameter as FlatParameter
  File "/path/to/Megatron-MS/Megatron-MS/torch/distributed/fsdp/_flat_param.py", line 45, in <module>
    from torch.testing._internal.distributed.fake_pg import FakeProcessGroup
ModuleNotFoundError: No module named 'torch.testing'
```

**Environment (please complete the following information):**
 - Megatron-LM commit ID
 - PyTorch version
 - CUDA version
 - NCCL version

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by Au3C2** [comment]
did not using fsdp
